to_do/urls.py
from django.urls import path

from to_do.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, toggle_task_is_done,
)

app_name = "to_do"

urlpatterns = [
    path("", TaskListView.as_view(), name="home"),
    path("create/", TaskCreateView.as_view(), name="home-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="home-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="home-delete"),
    path(
        "<int:pk>/toggle-is-done/",
        toggle_task_is_done,
        name="toggle-task-is-done",
    ),

    path("tags/", TagListView.as_view(), name="tags"),
    path("tags/create/", TagCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tags-delete"),
]

to_do_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do.urls", namespace="to_do"))
]

to_do/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        Tag,
        through="TaskTag",
        related_name="tasks",
        blank=True
    )

    class Meta:
        ordering = ["is_done", "-date_created"]


class TaskTag(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["task", "tag"],
                name="unique_task_tag"
            )
        ]

to_do/forms.py
from django import forms

from to_do.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("content", "date_deadline", "is_done", "tags",)
        widgets = {
            "date_deadline": forms.DateInput(attrs={
                "type": "date",
                "class": "form-control",
            }),
        }

to_do/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from to_do.forms import TaskForm
from to_do.models import Task, Tag


class TaskListView(ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "to_do/home.html"

    def get_queryset(self):
        return Task.objects.prefetch_related('tags').all()


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("to_do:home")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("to_do:home")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("to_do:home")

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        task.delete()
        return redirect(self.success_url)


def toggle_task_is_done(request, pk):
    task = Task.objects.get(id=pk)
    task.is_done = not task.is_done
    task.save()

    return redirect(reverse_lazy("to_do:home"))


class TagListView(ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "to_do/tags.html"


class TagCreateView(CreateView):
    model = Tag
    fields = ("name",)
    success_url = reverse_lazy("to_do:tags")


class TagUpdateView(UpdateView):
    model = Tag
    fields = ("name",)
    success_url = reverse_lazy("to_do:tags")


class TagDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("to_do:tags")

    def post(self, request, *args, **kwargs):
        tag = get_object_or_404(Tag, pk=kwargs["pk"])
        tag.delete()
        return redirect(self.success_url)

templates/base/_base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
  >

  {% block link %}
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"
    />
  {% endblock %}

  <title>{% block title %}{% endblock title %}</title>
</head>

<body>

<div class="container-fluid">
  <div class="row">

    <div class="col-sm-2">
      {% include "base/nav/_sidebar.html" %}
    </div>

    <div class="col-sm-10">
      {% block content %}
      {% endblock %}
    </div>

  </div>
</div>

</body>
</html>

templates/base/nav/_sidebar.html
<aside class="sidebar">

  <nav class="mt-3">
    <table class="table table-bordered">
      <tr>
        <td><a href="{% url 'to_do:home' %}" class="nav-link">Home</a></td>
      </tr>
      <tr>
        <td><a href="{% url 'to_do:tags' %}" class="nav-link">Tags</a></td>
      </tr>
    </table>
  </nav>

</aside>

templates/to_do/home.html
{% extends "base/_base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mt-3 mb-4">
    <h1>TODO list</h1>

    <a href="{% url 'to_do:home-create' %}" class="btn btn-primary">Add
      Task</a>
  </div>

  {% for task in task_list %}
    <div>
      <div class="d-flex justify-content-between align-items-center mt-3">
        <h5>
          <span>
            {{ task.content }}
          </span>

          {% if task.is_done %}
            <span style="color: green">Done</span>
          {% else %}
            <span style="color: red">Not done</span>
          {% endif %}
        </h5>

        {% if task.is_done %}
          <a href="{% url 'to_do:toggle-task-is-done' pk=task.id %}"
             class="btn btn-secondary">Undo</a>
        {% else %}
          <a href="{% url 'to_do:toggle-task-is-done' pk=task.id %}"
             class="btn btn-success">Complete</a>
        {% endif %}
      </div>

      <div>
        <p style="display: inline-block; margin: 0">
          Created: {{ task.date_created }}</p>
        {% if task.date_deadline %}
          <p style="display: inline-block; margin: 0; color: darkred">
            Deadline: {{ task.date_deadline }}</p>
        {% endif %}
      </div>

      {% if task.tags.all.count > 0 %}
        <p style="margin: 0">Tags:
          {% for tag in task.tags.all %}
            {{ tag.name }}{% if not forloop.last %} {% endif %}
          {% endfor %}
        </p>
      {% endif %}

      <div>
        <a href="{% url 'to_do:home-update' pk=task.id %}"
           class="btn btn-link">Update</a>
        <form style="display: inline-block"
              action="{% url 'to_do:home-delete' pk=task.pk %}" method="post">
          {% csrf_token %}
          <input type="submit" class="btn btn-link" value="Delete">
        </form>
      </div>
    </div>
    <hr style="color: #5050520d; opacity: 1;" class="mt-3">

  {% empty %}
    <p>There are no tasks.</p>

  {% endfor %}

{% endblock %}

templates/to_do/tag_form.html
{% extends "base/_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>{{ object|yesno:"Update,New" }} tag</h1>

    <label for="submit-form" class="btn btn-primary">
      {{ object|yesno:"Update,Add" }}
    </label>
  </div>

  <div>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input id="submit-form" type="submit" class="d-none">
    </form>
  </div>

{% endblock %}

templates/to_do/tags.html
{% extends "base/_base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>Tags</h1>

    <a href="{% url 'to_do:tags-create' %}" class="btn btn-primary">Add</a>
  </div>

  <div>
    {% if tag_list %}
      <table class="table table-borderless mt-2">
        <thead>
        <tr style="border-top: 1px solid lightgray">
          <th>Name</th>
          <th class="btn-column">Update</th>
          <th class="btn-column">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for tag in tag_list %}
          <tr style="border-top: 1px solid lightgray">
            <td class="content-column">{{ tag.name }}</td>
            <td>
              <a href="{% url 'to_do:tags-update' pk=tag.pk %}"
                 class="btn btn-secondary">Update</a>
            </td>
            <td>
              <form action="{% url 'to_do:tags-delete' pk=tag.pk %}"
                    method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-secondary" value="Delete">
              </form>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    {% else %}
      <p>There are no tags.</p>

    {% endif %}
  </div>

{% endblock %}

templates/to_do/task_form.html
{% extends "base/_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>{{ object|yesno:"Update,New" }} task</h1>

    <label for="submit-form" class="btn btn-primary">
      {{ object|yesno:"Update,Add" }}
    </label>
  </div>

  <div>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input id="submit-form" type="submit" class="d-none">
    </form>
  </div>

{% endblock %}